reclamos/config/routes.rb
Reclamos::Application.routes.draw do

 
 
  get "api/index"
  get "api/search"
  post "api/post_prueba"
  get "api/form_prueba"
 
  get "companies/accept", :as => 'companies_accept'
  match 'companies/accept/:id' => 'companies#aceptar'
  
  get "api/index", :as => 'api'
  
  
  post 'complaints/upload', :to => 'complaints#upload', :format => 'js'
  
  get "ajax/users"
  get "ajax/companies"
  get "ajax/companies_all"
  get "ajax/tags_all"
  get "ajax/msg_all"
  
  resources :companies
  
  resources :lawyer_invitations
  
  resources :users do
    member do
      get 'api'
      get 'generate_token'
      get 'change_password'
      post 'update_password'
    end
  end  
  
  resources :messages
  
  post "messages/create", :as => 'message_create'
  post "messages/send_message"

  resources :invitations do
    member do
      get 'accept'
      get 'reject'
      get 'hide_sent'
      get 'hide_received'
    end
  end 

  resources :users do
    member do
      get 'my_invitations'
    end
  end 

  
  resources :invitations
  
  get "lawyers/accept", :as => 'lawyers_accept'
  match 'lawyers/accept/:id' => 'lawyers#aceptar'

  resources :complaints do
    collection do
      get 'assign_cause'
      get 'select_existing_cause'
      put 'join_to_existing_cause'
      get 'add_tag'
      post 'tag_added'
      get 'remove_tag'
      get 'no_tag'
      post 'post_added'
      post 'post_removed'
    end
  end  
  
  resources :causes do
    collection do
      get 'new_with_complaint'
      post 'create_with_complaint'
    end
    member do
      get 'support'
      get 'unsupport'
      post 'defend'
      post 'solve'
    end
  end  
  
  get "home/index", :as => 'index'

  post "home/login", :as => 'login'

  get "home/logout", :as => 'logout'
  
  get "home/signup", :as => 'signup'
  
  post "home/signup", :as => 'signup'
  
  get "home/admin", :as => 'admin'
  
  get "home/messages", :as => 'messages'

  get "home/recover_password", :as => 'recover_password'
  post "home/send_password", :as => 'send_password'
  
  get "home/set_user_to_change_password", :as => 'set_user_to_change_password'
  
  post "home/go_to_user_change_password", :as => 'go_to_user_change_password'

  
  
  resources :complaints

  resources :lawyers do
    member do
      post 'defend_cause'
      post 'stop_defending_cause'
    end
  end
      
  
  resources :causes

  resources :users

  

root :to => 'home#index'

end

reclamos/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

reclamos/app/views/layouts/_header.html.erb
<% if current_user.nil? %>
    <fieldset id="loginBar">
      <div class="container">
             <%= form_tag login_path do %>
              <div class="field">
                <%= label_tag :username %>
                <input class="loginText" type="text" name="username" id="username">
              </div>
              <div class="field">
                <%= label_tag :password %>
                <input class="loginText" type="password" name="password" id="password">
              </div>
              <div class="field">
                <input id="loginButton" name="commit" type="submit" value="Log in">
              </div>
              <br><%= link_to "Recuperar contraseña", :action => "recover_password", :controller => "home" %> | <%= link_to "Registrate!", signup_path %> ¡es gratis!
            <% end %>
      </div>
    </fieldset>
<% end %>
<div class="clear"></div>

reclamos/app/views/layouts/_navigation.html.erb
          <li><%= link_to "Inicio",index_path %></li>
          <li><%= link_to "Reclamos",complaints_path %></li>
          <li><%= link_to "Causas", causes_path %> </li>
      <% if current_user.nil? == false %>
          <li><%= link_to "Abogados",lawyers_path %></li>
          <li><%= link_to "API", api_user_path(current_user) %> </li>
          <% if current_is_admin %>
            <li><%= link_to "Administración", admin_path , {:title =>"Panel de Administración"} %></li>
          <%end%>
          <li><%= link_to "Mi perfil", current_user , {:title =>"Mi perfil"} %></li>
        <li>
        <% if current_is_user %>
          <%= link_to "Invitaciones(#{invitations})", :controller => "users", :action => "my_invitations", :id => current_user.id %>
        <% end %>
        </li>
        <li><%= link_to "Mensajes ("+get_msg_count.to_s+")",:controller => "messages", :action => "index"%></li>
        <li><%= link_to "Logout",logout_path , {:title =>"Desconectarse"}%></li>
      <% end %>
      <div class="clear"></div>

reclamos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Reclamos" %></title>
    <link href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" type="text/css" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Ubuntu:300" rel="stylesheet" type="text/css">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'jquery', 'application' %>
    <script type="text/javascript" src="http://jzaefferer.github.com/jquery-validation/jquery.validate.js"></script>
  </head>
  <body>
    <!-- header -->
    <div class="fixposition">
      <div id="header-wrapper">
        <header id="header-content">
          <nav class="menu" id="menu">
            <ul>
              <%= render 'layouts/navigation' %>
            </ul>
          </nav>
          <%= render 'layouts/header' %>
        </header>
      </div>
    </div>
    <!-- end header -->
    <div id="wrapper">
      <div id="content">
        <%= yield %>
      </div>
    </div>
    <footer>
    </footer>
  </body>
</html>