reclamos/config/routes.rb
Reclamos::Application.routes.draw do

 
 
  get "api/index"
  get "api/search"
  post "api/post_prueba"
  get "api/form_prueba"
 
  get "companies/accept", :as => 'companies_accept'
  match 'companies/accept/:id' => 'companies#aceptar'
  
  get "api/index", :as => 'api'
  
  
  post 'complaints/upload', :to => 'complaints#upload', :format => 'js'
  
  get "ajax/users"
  get "ajax/companies"
  get "ajax/companies_all"
  get "ajax/tags_all"
  get "ajax/msg_all"
  
  resources :companies
  
  resources :lawyer_invitations
  
  resources :users do
    member do
      get 'api'
      get 'generate_token'
      get 'change_password'
      post 'update_password'
    end
  end  
  
  resources :messages
  
  post "messages/create", :as => 'message_create'
  post "messages/send_message"

  resources :invitations do
    member do
      get 'accept'
      get 'reject'
      get 'hide_sent'
      get 'hide_received'
    end
  end 

  resources :users do
    member do
      get 'my_invitations'
    end
  end 

  
  resources :invitations
  
  get "lawyers/accept", :as => 'lawyers_accept'
  match 'lawyers/accept/:id' => 'lawyers#aceptar'

  resources :complaints do
    collection do
      get 'assign_cause'
      get 'select_existing_cause'
      put 'join_to_existing_cause'
      get 'add_tag'
      post 'tag_added'
      get 'remove_tag'
      get 'no_tag'
      post 'post_added'
      post 'post_removed'
    end
  end  
  
  resources :causes do
    collection do
      get 'new_with_complaint'
      post 'create_with_complaint'
    end
    member do
      get 'support'
      get 'unsupport'
      post 'defend'
      post 'solve'
    end
  end  
  
  get "home/index", :as => 'index'

  post "home/login", :as => 'login'

  get "home/logout", :as => 'logout'
  
  get "home/signup", :as => 'signup'
  
  post "home/signup", :as => 'signup'
  
  get "home/admin", :as => 'admin'
  
  get "home/messages", :as => 'messages'

  get "home/recover_password", :as => 'recover_password'
  post "home/send_password", :as => 'send_password'
  
  get "home/set_user_to_change_password", :as => 'set_user_to_change_password'
  
  post "home/go_to_user_change_password", :as => 'go_to_user_change_password'

  
  
  resources :complaints

  resources :lawyers do
    member do
      post 'defend_cause'
      post 'stop_defending_cause'
    end
  end
      
  
  resources :causes

  resources :users

  

root :to => 'home#index'

end

reclamos/app/models/complaint.rb
require 'net/http'
require 'net/https'
require 'uri'
require 'json'

class Complaint < ActiveRecord::Base
  attr_accessible :frequent,:views, :name, :problem_date, :state, :description, :company_id, :cause_id,:company_name, :company
  
  belongs_to :creator, :class_name => "User"
  belongs_to :company
  belongs_to :cause
  
  has_many :documents,:dependent => :destroy
  has_many :posts,:dependent => :destroy
  
  has_and_belongs_to_many :tags
  
  validates :company_id, :presence => true
  
  def likes
  
    url = 'http://www.facebook.com/reclamos_cafe2/complaints/' + id.to_s
    json_s = get_facebook_stats(url)
    json_obj = JSON.parse(json_s)
    json_obj[0]["total_count"]
  
    
  end
  
  #http://stackoverflow.com/questions/7178590/facebook-fql-query-with-ruby
  def get_facebook_stats(url)

    params = {
        :query => 'SELECT total_count FROM link_stat WHERE url = "' + url + '"',
        :format => 'json'
    }

    http = http_get('api.facebook.com', '/method/fql.query', params)
    http

  end
  
  def http_get(domain,path,params)
    path = path + "?" + params.collect { |k,v| "#{k}=#{CGI::escape(v.to_s)}" }.join('&')
    request = Net::HTTP.get(domain, path)
  end
  
  def company_name
    company.name if company
  end

  def company_name=(name)
    unless name.blank?
      @company = Company.find_by_name(name)
      if @company then
        self.company = @company
      else
        @company = Company.new
        @company.update_attributes(:password => '123456',:state => '0',:name => name)
        if @company.save
          self.company = @company
        end
      end
    end
  end
end

reclamos/app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  # GET /complaints
  # GET /complaints.json
  
  def index  
    searched_tag = params[:tag]
    my_complaints = params[:my_complaints]
    not_existing_tag = false
    
    
    
    if (searched_tag != nil)
      tag = Tag.find_by_text(searched_tag)
      if tag != nil       
        @complaints = tag.complaints
      else
        not_existing_tag = true
      end
    elsif my_complaints
      @complaints = current_user.created_complaints.order(:created_at => :asc)
    else
      @complaints = Complaint.all
    end
    
    
    
    
    if not_existing_tag
      redirect_to no_tag_complaints_url
    else
      @complaints.sort! { |a,b| b.likes <=> a.likes }  
      respond_to do |format|
        format.html # index.html.erb
        format.json do
          @access_token = params[:access_token]
          if @access_token
            @complaints = User.find_by_access_token(@access_token).created_complaints
          end
          render json: @complaints 
        end
      end
    end
    
  end

  # GET /complaints/1
  # GET /complaints/1.json
  def show
    @complaint = Complaint.find(params[:id])
    @cause =  Cause.find_by_id(@complaint.cause_id)
    @tags = @complaint.tags
    
    @complaint.update_attributes(:views => (1 + @complaint.views))
    
    if @cause.nil? == false 
      @cause_name =  @cause.name
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @complaint }
    end
  end

  # GET /complaints/new
  # GET /complaints/new.json
  def new
    if current_account == 'user'
      @complaint = Complaint.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @complaint }
      end
    else
      redirect_to index_path
    end
  end

  # GET /complaints/1/edit
  def edit
    @complaint = Complaint.find(params[:id])
  end

  # POST /complaints
  # POST /complaints.json
  def create
    @token = params[:access_token]
    @complaint = Complaint.new(params[:complaint])
        

    if @token
      p = {}
      p[:frequent] = params[:frequent]
      p[:name] = params[:name]
      p[:problem_date] = params[:description]
      p[:company_name] = params[:company_name]
      @complaint = Complaint.new(p)
      @complaint.creator = User.find_by_access_token(@token)
    elsif current_user
      @complaint = Complaint.new(params[:complaint])
      @complaint.creator = current_user;
    end
    
       
    if @complaint.creator
      save = @complaint.save
    end
       
    if current_user && !@token
      files = params['files']
    end
    
    if files and save
      files.each_key{ |key| 
        document = Document.uploadFile(key,files[key])
        document.complaint = @complaint
        document.save
        @complaint.documents << document
      }
    end
    
    respond_to do |format|
      if save && !@token
        format.html { redirect_to assign_cause_complaints_url(:complaint_id => @complaint.id), notice: 'El reclamo fue creado con exito. Ahora debes asignarle una causa' }
        format.json { render json: @complaint, status: :created, location: @complaint }
     elsif save && @token
      format.html { redirect_to @complaint }
      format.json { render json: @complaint }
        
     else
        format.html { render action: "new", notice: 'Debes estar logueado para crear un reclamo' }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }

     end
    end
  end

  # PUT /complaints/1
  # PUT /complaints/1.json
  def update
    @complaint = Complaint.find(params[:id])
    
    save = @complaint.update_attributes(params[:complaint])
    
    files = params['files']
    
    if files and save
      files.each_key{ |key| 
        document = Document.uploadFile(key,files[key])
        document.complaint = @complaint
        document.save
        @complaint.documents << document
      }
    end
    
    respond_to do |format|
      if save
        format.html { redirect_to complaints_url, notice: 'Complaint was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /complaints/1
  # DELETE /complaints/1.json
  def destroy
    @complaint = Complaint.find(params[:id])
    @complaint.destroy

    respond_to do |format|
      format.html { redirect_to complaints_url }
      format.json { head :no_content }
    end
  end
  
  def assign_cause
    @complaint = Complaint.find(params[:complaint_id])    
  end
  
  def select_existing_cause
    @complaint = Complaint.find(params[:complaint_id]) 
    
    @valid_causes = @complaint.company.causes
    if (@valid_causes == [])
      @valid_causes = nil
    end
    
  end
  
  #PUT /complaint/1/join_to_existing_cause  
  def join_to_existing_cause
    @complaint = Complaint.find(params[:complaint_id])
    @cause = Cause.find(params[:cause][:id])  
    @complaint.cause_id = @cause.id
    @complaint.save      
  end
  
  #GET 
  def add_tag
    @complaint = Complaint.find(params[:complaint_id])
  end
  
  
  #POST
  def tag_added
    @complaint = Complaint.find(params[:complaint_id])
    @tag_text = params[:new_tag]
    
    @length = @complaint.tags.length
    
    @existing_tag = Tag.find_by_text(@tag_text)
    
    @tag
       
    if @existing_tag
      @tag = @existing_tag
      if !@complaint.tags.include?(@existing_tag)
        @complaint.tags << @existing_tag
        @existing_tag = false
      else
        @existing_tag = true
      end
    else          
      @new_tag  = Tag.new(:text => @tag_text)
      @tag = @new_tag
    
      
      if @new_tag.save
        @complaint.tags << @new_tag
        @complaint.save
      end
    end
      
    respond_to do |format|
      format.html { redirect_to @complaint }
      format.js { }
    end
  end
  
  #GET  
  def remove_tag
    @complaint = Complaint.find(params[:complaint_id])
    @tag = Tag.find(params[:tag_id])
    @complaint.tags.delete(@tag)
    
    if @tag.complaints == [] || @tag.complaints == nil
      @tag.delete
    end
    
    redirect_to @complaint
   
  end
  
  def no_tag
  end
  
  
  #POST
  def post_added
    @complaint = Complaint.find(params[:complaint_id])
    if !params[:new_post].blank? 
      @post = Post.new
      @post.text = params[:new_post]
      @post.username = current_user.username
      @post.complaint = @complaint
      @post.save
    end
    respond_to do |format|
      format.html { redirect_to @complaint }
      format.js { }
    end
  end
  
  #POST
  def post_removed
    post = Post.find(params[:delete_post])
    @complaint = post.complaint
    post.destroy()
    respond_to do |format|
      format.html { redirect_to @complaint }
      format.js { }
    end
  end
  
end

reclamos/app/helpers/complaints_helper.rb
module ComplaintsHelper
end

reclamos/app/views/complaints/_form.html.erb
<div class='complaint'>

<% if flash[:notice] %>
  <p> <class="notice"><%= flash[:notice] %></p>
<% end %>

<%= form_for(@complaint,:html => { :multipart => true }) do |f| %>
  <% if @complaint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@complaint.errors.count, "error") %> prohibited this complaint from being saved:</h2>

      <ul>
      <% @complaint.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label 'El problema, ¿ocurre con frecuencia?' %>
    <%= f.select :frequent,{ 'Una vez'=>false, 'Varias veces'=>true } %>
  </div>
  <div class="field" id='problem_date'>
    <%= f.label :problem_date,'Fecha del problema' %>
    <%= f.date_select :problem_date %>
  </div>
  <div class="field">
    <%= f.label :name,'Titulo' %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :company_name,'Empresa'%> 
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label 'Descripcion' %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= label_tag 'Evidencias'%>
    <%= submit_tag "Agregar nuevo archivo", :type => 'button',:id => 'upload', :class => 'btn btn-success btn-small' %>
  </div>
  <div class="actions">
    <%= f.submit 'Enviar Reclamo', :class => 'btn btn-primary btn-small' %>
  </div>
<% end %>

</div>

reclamos/app/views/complaints/_new_tag.html.erb
<% if !@existing_tag %>
  <% if @length != 0%>
    <%= " " %>
  <% end %>
  <% if current_user==@complaint.creator %>
      <%= link_to @tag.text,complaints_path(:tag => @tag.text) %>
  <% else %>
      <%= link_to @tag.text,complaints_path(:tag => @tag.text) %>
  <% end %>
<% end %>

reclamos/app/views/complaints/add_tag.html.erb
<h3>Agregar tag </h3>
<%= form_tag(tag_added_complaints_path(:complaint_id => @complaint.id), :method => "post") do %>
  <%= label_tag(:new_tag, "Nuevo tag") %>
  <%= text_field_tag(:new_tag) %>
  <%= submit_tag("Agregar") %>
<% end %>

reclamos/app/views/complaints/assign_cause.html.erb
<% if (flash[:notice]) %>
  <%= flash[:notice] %>
<% end %>

<p> Para que tu reclamo pueda ser apoyado y defendido, debes asignarle una causa. </p>
<p>¿Deseas asignarle ahora una causa?</p>

<p><%= link_to "Crear nueva causa para el reclamo", new_with_complaint_causes_url(:complaint_id => @complaint.id) %></p>




<p><%= link_to "Agregarlo a una causa existente", select_existing_cause_complaints_url(:complaint_id => @complaint.id) %></p>

reclamos/app/views/complaints/create.html.erb
params <%= params %><br>
token <%= @token %><br>
params name <%= params[:name] %><br>
company name <%= params[:company_name] %><br>
company id <%= Company.find_by_name(params[:company_name]).id %><br>
creator <%= User.find_by_access_token(@token) %><br>
hash <%= @p%>

reclamos/app/views/complaints/edit.html.erb
<h1>Editing complaint</h1>

<%= render 'form' %>

<%= link_to 'Ver', @complaint %> |
<%= link_to 'Volver', complaints_path %>

reclamos/app/views/complaints/index.html.erb
<h1>Reclamos</h1>
  <% if session[:account]=='user' %>
      <%= link_to 'Crear nuevo reclamo', new_complaint_path,:class => 'btn btn-primary btn-large' %>
  <% end %>
  <%= form_tag(complaints_path, :method => "get") do %>
    <%= text_field_tag(:tag) %>
    <%= submit_tag("Buscar Tag") %>
  <% end %>
  
  <% if current_is_user %>
    <div><%= link_to "Mis Reclamos", complaints_path(:my_complaints => true) %></div>
    <div><%= link_to "Todos los reclamos", complaints_path %></div>
  <% end %>

  <ul id="complaints_list">
    <% @complaints.each do |complaint| %>
      <li>
        <dl class="complaints">
          <span class="complaint_name">
            <%= link_to complaint.name,complaint, :title => 'Ver reclamo' %>
          </span>
          <span class="right"> 
            <% if complaint.views.nil? %>
              Visto 0 veces
            <% else %>
              Visto <%= complaint.views %> veces
            <% end %>
          </span>
          
          <% if current_is_admin==true or (current_user==complaint.creator) %>
          <%= link_to (image_tag('eliminar.gif', :size => '20x20')) , complaint, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
          <br/>
          por <strong><%= link_to complaint.creator.username,complaint.creator, :title =>'Ver creador' %></strong> >> <%= I18n.localize(complaint.created_at,:format => :short) %>
          <br>
          <i class='tags-i' id='tags-i'>Tags: 
            <% if complaint.tags.length > 0 %>
              <% complaint.tags.each do |t| %>
                <%= link_to t.text,complaints_path(:tag => t.text) %>
              <% end %>
            <% else %>
              no tiene
            <% end %>
          </i>
        </dl>
      </li>
    <% end %>
  </ul>

reclamos/app/views/complaints/join_to_existing_cause.html.erb
<p> Se ha asociado exitosamente el reclamo <%= @complaint.name %> a la causa <%= @cause.name %>

reclamos/app/views/complaints/new.html.erb
<%= render 'form' %>

reclamos/app/views/complaints/no_tag.html.erb
No existen reclamos con ese tag

reclamos/app/views/complaints/select_existing_cause.html.erb
<p> Recuerda que solo puedes asociarlo a una causa de la misma empresa. </p>


<% if @valid_causes %>
  <p> Seleccione la causa a la que lo quiere asociar </p>

  <%= form_tag(join_to_existing_cause_complaints_url(:complaint_id => @complaint.id), :method => "put") do %>
    <%= collection_select(:cause, :id, @complaint.company.causes, :id, :name) %>
    <%= submit_tag("Asociar a causa") %>
  <% end %>
  
<% else %>

<p> No hay causas para esa empresa. Te recomendamos que crees una causa nueva para tu reclamo </p>

<% end %>

reclamos/app/views/complaints/show.html.erb
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class='complaint'>
  <div class='complaint-container sombra-linda'>
    <span class='complaint-subtitle'>
      <%=link_to @complaint.company_name,@complaint.company %> - 
    </span>
    <span class='complaint-title'>
      <%= @complaint.name %>
    </span>
    <p class='complaint-info'>
      <span class='complaint-author'>
        por <span class="creator_name"><%= link_to @complaint.creator.username,@complaint.creator, :title =>'Ver creador' %></span>
        <%= I18n.localize(@complaint.created_at,:format => :long) %>
      </span>
        <span class='complaint-btn'>
      <% if current_is_admin==true or (current_user==@complaint.creator) %>
        <%= link_to 'Editar', edit_complaint_path(@complaint),:class => 'btn btn-primary btn-small' %>
        <% if @cause.nil? %>
          <%= link_to 'Asociar Causa', assign_cause_complaints_url(:complaint_id => @complaint.id),:class => 'btn btn-primary btn-small' %>
        <% end %>
        <%= link_to 'Eliminar', @complaint,method: :delete,:class => 'btn btn-danger btn-small' %>
      <% end %>
    </span>
    </p>

    <p class='complaint-description'><%= @complaint.description %></p>
    
    <% if @cause %>
      <h2 class='complaint-attach'>Causa asociada</h2>
      <p class='complaint-cause'><%= link_to @cause.name,@cause %></p>
    <% end %>
  </div>
  
  <div class='complaint-tags-div sombra-linda'>
    <h2 class='complaint-attach'>Archivos adjuntos</h2>
      <% if @complaint.documents.length>0 then %>
        <ul class='complaint-attach-list'>
          <% @complaint.documents.each do |d| %>
            <li><%= link_to d.name,'../assets/uploads/'+d.path %></li>
          <% end %>
        </ul>
      <% else %>
        No tiene archivos adjuntos
      <% end %>
    </div>
  
  <div class='complaint-tags-div'>
    <div class='complaint-tags' id='tags_list'>
      <% if current_user == @complaint.creator %>
          <i class='tags-i' id='tags-i'>Tags: 
            <% if @complaint.tags.length > 0 %>
              <% @complaint.tags.each do |t| %>
                <%= link_to t.text,complaints_path(:tag => t.text) %>
              <% end %>
            <% end %>
          </i>
      <% else %>
          <i class='tags-i' id='tags-i'>Tags: 
            <% if @complaint.tags.length > 0 %>
              <% @complaint.tags.each do |t| %>
                <%= link_to t.text,complaints_path(:tag => t.text) %>
              <% end %>
            <% else %>
              no tiene
            <% end %>
          </i>
      <% end %>
      </div>
    </div>
    
    <% if current_user == @complaint.creator %>
      <div id='new-tag-buttons'>
        <div id='new-tag-div'>
      <%= form_tag(tag_added_complaints_path(:complaint_id => @complaint.id), :method => "post", :remote => true,:id => 'create_tag') do %>
          <%= text_field_tag :new_tag,'',:placeholder => 'Nombre tag',:class=>'left' %>
          <%= submit_tag "Agregar",:class=>'btn btn-primary btn-small left' %>
      <% end %>
        </div>
        <span id='new_tag_invalid'></span>
        <input type='button' class='btn btn-primary btn-small' id='new-tag-button' value='Nuevo tag'>
        <div class='clear'></div>
      </div>
    <% end %>
      <div class="fb-like" data-href="/reclamos_cafe2/complaints/<%=@complaint.id%>" data-send="true" data-layout="button_count" data-width="450" data-show-faces="true"></div>  
  
  <div id='posts_list' class='posts_list sombra-linda'>
    <!-- LISTA POSTS -->
    <% if @complaint.posts then %>
      <h2 class='comentario'>Comentarios</h2>
      <% @complaint.posts.each do |p| %>
        <div class='post'>
          <div class='post-info'>
            <div class='left'>
            <span class='complaint-author'>
              <span class='creator_name'><%= link_to p.username,get_account_by_username(p.username) %></span> hace <%= time_ago_in_words(p.created_at) %>
            </span>
            </div>
            <%= form_tag(post_removed_complaints_path(:delete_post => p.id), :method => "post") do %>
              <%= submit_tag 'X',:class=>'btn btn-danger btn-small right',:title=>'Eliminar'%>
            <% end %>
            <div class="clear"></div>
          </div>
          <p class='post-body'>
            <%= p.text %>
          </p>
        </div>
      <% end %>
    <% end %>

    <!-- LISTA POSTS -->
  </div>
  <!-- POST NUEVO -->
  <% if current_user %>
    <div class='new_post'>
      <%= form_tag(post_added_complaints_path(:complaint_id => @complaint.id), :method => "post", :remote => true,:id => 'create_comment') do %>
          <%= text_area_tag :new_post,'',:placeholder => 'Escribe un comentario',:id=>'new_post',:rows => 10, :cols => 60 %><br>
          <%= submit_tag "Enviar comentario",:class=>'btn btn-primary btn-small' %> <span id='new_post_invalid'></span>
      <% end %>
    </div>
  <% end %>
  <!-- POST NUEVO -->
</div>

reclamos/app/views/complaints/tag_added.html.erb
Reclamo <%= @complaint.name %>
Tag <%= @tag_text %>