reclamos/config/routes.rb
Reclamos::Application.routes.draw do

 
 
  get "api/index"
  get "api/search"
  post "api/post_prueba"
  get "api/form_prueba"
 
  get "companies/accept", :as => 'companies_accept'
  match 'companies/accept/:id' => 'companies#aceptar'
  
  get "api/index", :as => 'api'
  
  
  post 'complaints/upload', :to => 'complaints#upload', :format => 'js'
  
  get "ajax/users"
  get "ajax/companies"
  get "ajax/companies_all"
  get "ajax/tags_all"
  get "ajax/msg_all"
  
  resources :companies
  
  resources :lawyer_invitations
  
  resources :users do
    member do
      get 'api'
      get 'generate_token'
      get 'change_password'
      post 'update_password'
    end
  end  
  
  resources :messages
  
  post "messages/create", :as => 'message_create'
  post "messages/send_message"

  resources :invitations do
    member do
      get 'accept'
      get 'reject'
      get 'hide_sent'
      get 'hide_received'
    end
  end 

  resources :users do
    member do
      get 'my_invitations'
    end
  end 

  
  resources :invitations
  
  get "lawyers/accept", :as => 'lawyers_accept'
  match 'lawyers/accept/:id' => 'lawyers#aceptar'

  resources :complaints do
    collection do
      get 'assign_cause'
      get 'select_existing_cause'
      put 'join_to_existing_cause'
      get 'add_tag'
      post 'tag_added'
      get 'remove_tag'
      get 'no_tag'
      post 'post_added'
      post 'post_removed'
    end
  end  
  
  resources :causes do
    collection do
      get 'new_with_complaint'
      post 'create_with_complaint'
    end
    member do
      get 'support'
      get 'unsupport'
      post 'defend'
      post 'solve'
    end
  end  
  
  get "home/index", :as => 'index'

  post "home/login", :as => 'login'

  get "home/logout", :as => 'logout'
  
  get "home/signup", :as => 'signup'
  
  post "home/signup", :as => 'signup'
  
  get "home/admin", :as => 'admin'
  
  get "home/messages", :as => 'messages'

  get "home/recover_password", :as => 'recover_password'
  post "home/send_password", :as => 'send_password'
  
  get "home/set_user_to_change_password", :as => 'set_user_to_change_password'
  
  post "home/go_to_user_change_password", :as => 'go_to_user_change_password'

  
  
  resources :complaints

  resources :lawyers do
    member do
      post 'defend_cause'
      post 'stop_defending_cause'
    end
  end
      
  
  resources :causes

  resources :users

  

root :to => 'home#index'

end

reclamos/app/models/user.rb
class User < ActiveRecord::Base
  has_many :created_complaints, :foreign_key => "creator_id", :class_name => "Complaint", :dependent => :destroy
  
  has_many :causes, :through => :supports
  has_many :supports
  
  has_many :sent_invitations, :class_name => "Invitation", :foreign_key => "inviting_id",:dependent => :destroy
  has_many :received_invitations, :class_name => "Invitation", :foreign_key => "invited_id",:dependent => :destroy
  
  has_many :posts,:dependent => :destroy
  
  has_many :recovery_codes
  
  attr_accessible :email, :first_name, :last_name, :password, :username, :admin, :access_token
  
  has_secure_password
  
  validates :email, :presence => true, :uniqueness => true
  validates :username, :presence => {true => "Debe ingresar un Username"}, :uniqueness => true
  validates :password, :presence => true, :length => {:minimum => 6,:maximum => 20,:too_short => "Lo minimo permitido son %{count} letras",:too_long => "Lo maximo permitido son %{count} letras"}
  
  validate :lawyer_and_company_username_exists
  
  private
  def lawyer_and_company_username_exists
    l = Lawyer.find_by_username(self.username)
    c = Company.find_by_username(self.username)
    if(l or c)
      #errors.add_to_base(:username,"El username ya existe")
      errors[:base] << "El username ya existe"
    end
  end
  
end

reclamos/app/controllers/users_controller.rb
class UsersController < ApplicationController

  # mostramos los subscritos
  #def show_users_of_complaint
  #  @users = User.find_all_by_complaint_id(params[:id])
  #  render :index
  #end

  def users_ajax
    if params[:term]
      like= "%".concat(params[:term].concat("%"))
      users = User.where("username like ?", like)
    else
      users = User.all
    end
    list = users.map {|u| Hash[ id: u.id, label: u.username, name: u.username]}
    render json: list
  end


  # GET /users
  # GET /users.json
  def index
    @users = User.all
    
      if current_is_admin
        respond_to do |format|
          format.html 
          format.json { render json: @users }
        end
      else
        render :inline => 'Debe ser admin para ver esto.', :layout => true
      end  

  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    
    #UserMailer.welcome_email(@user).deliver

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    if current_is_admin 

      @user = User.new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @user }
      end
    else
      redirect_to index_path
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    if current_is_admin or current_user == @user
      @user = User.find(params[:id])
    else
      redirect_to index_path
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save    
        
#        UserMailer.welcome_email(@user).deliver
           
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
  
  def my_invitations
    @received = current_user.received_invitations
    @sent = current_user.sent_invitations
        
    @received_is_empty = true
    if !@received.empty?
      @received.each do |i|
        if i.visible_to_invited
          @received_is_empty = false
        end
      end
    else
      @received_is_empty = true
    end
    
    @sent_is_empty = true
    if !@sent.empty?
      @sent.each do |i|
        if i.visible_to_inviting
          @sent_is_empty = false
        end
      end
    else
      @sent_is_empty = true
    end  
    
    
    
  end
  
  
  # GET /users/1/change_password
  def change_password
    @user = User.find(params[:id])
  end
  
  # POST /users/1/update_password
  def update_password
    @user = User.find(params[:id])
    
    @new_password = params[:password]
    @code = RecoveryCode.find_by_code(params[:code_number])
       
    if @user.recovery_codes.include?(@code)
      @contains = true        
      if @user.update_attributes(:password => @new_password)
        @code.delete
        @modificado = true
      end
    end
  end
  
  
  def api
    @user = User.find(current_user.id)
    @token = @user.access_token
    
  end
  
  def generate_token
    user = User.find(current_user.id)
    token = Random.rand(1000000..2000000)
    user.update_attribute(:access_token, token)
    
    redirect_to api_user_path(current_user)
    
  end
   
end

reclamos/app/helpers/users_helper.rb
module UsersHelper
end

reclamos/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="actions">
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

reclamos/app/views/users/api.html.erb
<% if @token == nil %>
Aun no has usado la API. Para usarla necesitas <%= link_to "generar un token", generate_token_user_url(current_user) %>

<% else %>
<%= @user.first_name %>, tu access_token para la API es <%= @token %>
<!--
<p>
Para acceder a todos los reclamos debes ingresar la URL
<%= link_to "http://localhost:3000/complaints.json", "http://localhost:3000/complaints.json" %>
</p>
<p>
Para acceder solo a los reclamos creados por ti deber ingresar la URL
http://localhost:3000/complaints.json? + access_token=[TU ACCESS TOKEN]<br>
<%= link_to "http://localhost:3000/complaints.json?access_token=" + @token.to_s , "http://localhost:3000/complaints.json?access_token=" + @token.to_s %>
</p>-->
<% end %>

reclamos/app/views/users/change_password.html.erb
<h1> Cambiar contraseña </h2>
<p> Usuario: <%= @user.username %> </p>

<%= form_tag(:controller => "users", :action => "update_password", :id => @user.id, :code_number => @code_number) do %>
  <div class="field">
    <%= label_tag :code_number,  "Codigo de recuperacion" %><br />
    <%= text_field_tag :code_number %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">  
    <%= submit_tag("Cambiar contrasenia") %>
  </div>
<% end %>

reclamos/app/views/users/create.html.erb
algocsdodn

reclamos/app/views/users/edit.html.erb
<h1>Editar perfil</h1>

<%= render 'form' %>

<%= link_to 'Back', @user %>

reclamos/app/views/users/index.html.erb
<% if current_is_admin == true %>
  <%= render "home/admin_header" %>
  <div id="admin_content">
<% end %>

<% if @users.count > 0 %>

  <h1>Usuarios</h1>

  <table>
    <tr>
      <th>Username</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Email</th>
    <% if current_is_admin == true %>
      <th></th>
      <th></th>
      <th></th>
    <% end %>
    </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
    <% if current_is_admin == true %>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <% end %>
    </tr>
  <% end %>
  </table>
<% end %>

<% if current_is_admin == true %>
  </div>
  <%= render "home/admin_footer" %>
<% end %>

reclamos/app/views/users/my_invitations.html.erb
<div>
  <%= link_to "Invitar usuario ", new_invitation_path, :class=>'btn btn-large btn-success', :title => 'Invita a un usuario a apoyar causas!' %>
</div>
<!--<div>
  <%= link_to "Invitar abogado ", new_lawyer_invitation_path, :class=>'btn btn-large btn-success' %> Invita a un abogado a defender una causa.
<div>-->
<h1> Invitaciones pendientes </h1>


<h2> Enviadas </h2>

<% if !@sent_is_empty %>
  <p> Has invitado usarios a apoyar las siguientes causas </p>
  <% @sent.each do |invitation| %>
  
  <%if invitation.visible_to_inviting %>
    <table>
      <tr>
        <td>
        <%= link_to "#{invitation.cause.name}", invitation.cause %>
        Enviada a <%= link_to "#{invitation.invited.username}", invitation.invited %> 
        <% if invitation.state == 0 %>
           Invitación pendiente    
          <% elsif invitation.state == 1 %>
            Invitación aceptada <%= link_to "Borrar de la lista", hide_sent_invitation_path(invitation) %>
          <% else %>
            Invitación rechazada <%= link_to "Borrar de la lista", hide_sent_invitation_path(invitation) %>
          
       </td>
      </tr>
      
    </table>
    <% end %>
  <%end %>  
<% end %>
<% else %>
  <p> No tienes invitaciones enviadas pendientes </p>
<% end %>




<h2> Recibidas</h2>


<% if !@received_is_empty %>
  <p> Te han invitado a apoyar las siguientes causas </p>
  <% @received.each do |invitation| %>
    <%if invitation.visible_to_invited %>  
      <table>
        <tr>
          <td>
            <%= link_to "#{invitation.cause.name}", invitation.cause %>
            Enviada por <%= link_to "#{invitation.inviting.username}", invitation.inviting %> 
            <% if invitation.state == 0 %>
              <%= link_to "Aceptar", accept_invitation_path(invitation)  %> <%= link_to "Rechazar", reject_invitation_path(invitation)  %>    
            <% elsif invitation.state == 1%>
              Invitación aceptada <%= link_to "Borrar de la lista", hide_received_invitation_path(invitation) %>
            <% else %>
              Invitación rechazada <%= link_to "Borrar de la lista", hide_received_invitation_path(invitation)%>
            <% end %>
         </td>
        </tr>
      <table>
    <% end %>
  <% end %>
<% else %>
  <p> No tienes invitaciones recibidas pendientes </p>
<% end %>

reclamos/app/views/users/new.html.erb
<h1>Registro</h1>

<div class="new_user">
  <%= render 'form' %>
</div>

reclamos/app/views/users/show.html.erb
<% if current_is_admin == true %>
  <%= render "home/admin_header" %>
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<% if current_is_admin==true or (current_user==@user) %>
  <%= link_to 'Editar', edit_user_path(@user),  :class => 'btn btn-primary btn-small' %>
<% end %>

<% if current_is_admin == true %>
  <%= render "home/admin_footer" %>
<% end %>

reclamos/app/views/users/update_password.html.erb
<!--
nueva pass <%= @new_password %> <br>
codigo <%= @code %> <br>
-->

<% if @contains && !@modificado %>
El codigo es correcto, pero no se modifica la pass
<% elsif @modificado %>
La contraseña se ha modificado
<% else %>
 El código es inválido
<% end %>