reclamos/config/routes.rb
Reclamos::Application.routes.draw do

 
 
  get "api/index"
  get "api/search"
  post "api/post_prueba"
  get "api/form_prueba"
 
  get "companies/accept", :as => 'companies_accept'
  match 'companies/accept/:id' => 'companies#aceptar'
  
  get "api/index", :as => 'api'
  
  
  post 'complaints/upload', :to => 'complaints#upload', :format => 'js'
  
  get "ajax/users"
  get "ajax/companies"
  get "ajax/companies_all"
  get "ajax/tags_all"
  get "ajax/msg_all"
  
  resources :companies
  
  resources :lawyer_invitations
  
  resources :users do
    member do
      get 'api'
      get 'generate_token'
      get 'change_password'
      post 'update_password'
    end
  end  
  
  resources :messages
  
  post "messages/create", :as => 'message_create'
  post "messages/send_message"

  resources :invitations do
    member do
      get 'accept'
      get 'reject'
      get 'hide_sent'
      get 'hide_received'
    end
  end 

  resources :users do
    member do
      get 'my_invitations'
    end
  end 

  
  resources :invitations
  
  get "lawyers/accept", :as => 'lawyers_accept'
  match 'lawyers/accept/:id' => 'lawyers#aceptar'

  resources :complaints do
    collection do
      get 'assign_cause'
      get 'select_existing_cause'
      put 'join_to_existing_cause'
      get 'add_tag'
      post 'tag_added'
      get 'remove_tag'
      get 'no_tag'
      post 'post_added'
      post 'post_removed'
    end
  end  
  
  resources :causes do
    collection do
      get 'new_with_complaint'
      post 'create_with_complaint'
    end
    member do
      get 'support'
      get 'unsupport'
      post 'defend'
      post 'solve'
    end
  end  
  
  get "home/index", :as => 'index'

  post "home/login", :as => 'login'

  get "home/logout", :as => 'logout'
  
  get "home/signup", :as => 'signup'
  
  post "home/signup", :as => 'signup'
  
  get "home/admin", :as => 'admin'
  
  get "home/messages", :as => 'messages'

  get "home/recover_password", :as => 'recover_password'
  post "home/send_password", :as => 'send_password'
  
  get "home/set_user_to_change_password", :as => 'set_user_to_change_password'
  
  post "home/go_to_user_change_password", :as => 'go_to_user_change_password'

  
  
  resources :complaints

  resources :lawyers do
    member do
      post 'defend_cause'
      post 'stop_defending_cause'
    end
  end
      
  
  resources :causes

  resources :users

  

root :to => 'home#index'

end

reclamos/app/controllers/causes_controller.rb
class CausesController < ApplicationController
  # GET /causes
  # GET /causes.json
  def index
    @causes = Cause.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @causes }
    end
  end

  # GET /causes/1
  # GET /causes/1.json
  def show
    @cause = Cause.find(params[:id])
    @complaints = @cause.complaints
    @users = @cause.users
    @lawyer = @cause.lawyer
    @company = @cause.company
    
    @exists_request = nil
    
    
    if (current_is_lawyer)    
      @exists_request = DefenseRequest.where(:requesting_lawyer_id => current_user.id, :requested_cause_id => @cause.id)
    end
    
    
    if (@exists_request == [])
      @exists_request = nil
    end
    
    
    if (current_is_lawyer)
      @defend = true
    else
      @defend = false
    end
    
    
    @supports = false
    
    if @cause.users.include?(current_user)
      @supports = true                            
    end
    
    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cause }
    end
  end

  # GET /causes/new
  # GET /causes/new.json
  def new
    @cause = Cause.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cause }
    end
  end
  
  def new_with_complaint 
    @complaint = Complaint.find_by_id(params[:complaint_id])
    @company = Company.find(@complaint.company.id) 
     
    @cause = Cause.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cause }
    end
  end

  # GET /causes/1/edit
  def edit
    @cause = Cause.find(params[:id])
  end

  # POST /causes
  # POST /causes.json
  def create
    @cause = Cause.new(params[:cause])
    
    respond_to do |format|
      if @cause.save
        format.html { redirect_to @cause, notice: 'Cause was successfully created.' }
        format.json { render json: @cause, status: :created, location: @cause }
      else
        format.html { render action: "new" }
        format.json { render json: @cause.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def create_with_complaint
    @access_token = params[:access_token]
    @complaint_id = params[:complaint_id]
    @complaint = Complaint.find_by_id(@complaint_id)
     
    @cause_hash = {}
     
    @cause_hash[:company_id] = params[:company_id]
    @cause_hash[:description] = params[:description]
    @cause_hash[:name] = params[:name]

     
    @cause = Cause.new(@cause_hash)  
    
    
    if @access_token
      @creator = User.find_by_access_token(@access_token)
    else
      @creator = current_user
    end
    
    if @creator
      save = @cause.save
    end
     
    if save
      @cause.complaints << @complaint     
      @cause.users << @creator
      @support = Support.where(:user_id => @creator.id, :cause_id => @cause.id)[0]
           
      @support.is_owner = true
      
      @support.save
      
      
      respond_to do |format|
        format.html { redirect_to @complaint, notice: "La causa para el reclamo fue creada con exito"}
        format.json { render json: @cause }
      end

    end
      
  end

  # PUT /causes/1
  # PUT /causes/1.json
  def update
    @cause = Cause.find(params[:id])

    respond_to do |format|
      if @cause.update_attributes(params[:cause])
        format.html { redirect_to @cause, notice: 'Cause was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cause.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /causes/1
  # DELETE /causes/1.json
  def destroy
    @cause = Cause.find(params[:id])
    @cause.destroy

    respond_to do |format|
      format.html { redirect_to causes_url }
      format.json { head :no_content }
    end
  end
  
  #GET
  def support
    @cause = Cause.find(params[:id])
    
    @supports = false
    
    if @cause.users.include?(current_user)
      @supports = true
    end    
    
    if current_user != nil && !@supports
      @cause.users << current_user
      redirect_to @cause
    end
  end
  
  #GET
  def unsupport
    @cause = Cause.find(params[:id])
    
    @supports = false   
    if @cause.users.include?(current_user)
      @supports = true
    end
    
    if current_user != nil && @supports
      @cause.users.delete(current_user)
      redirect_to @cause
    end      
  end
  
  #POST
  def defend
    @cause = Cause.find(params[:id])
    if current_is_lawyer
      @existing_request = @cause.requesting_lawyers.where(:id => current_user.id)
      if @existing_request != nil && !@existing_request.empty?
        redirect_to @cause, notice: 'Usted ya mando una solicitud de defensa para esta causa'
      else
        @dr = DefenseRequest.new(:requesting_lawyer_id => current_user.id, :requested_cause_id => @cause.id)
        if @dr.save
          redirect_to @cause, notice: 'Se le ha enviado al creador de la causa una solicitud de defensa'
        end
      end
    end
  end
  
  #POST
  def solve
    @cause = Cause.find(params[:id])
    @cause.update_attributes(:state => 2)
    redirect_to @cause
  end
  
end

reclamos/app/helpers/causes_helper.rb
module CausesHelper

  def list_complaints(complaints)
    complaints.each{|x| yield(x)}
  end
  
  def list_users(users)
    users.each{|x| yield(x)}
  end
 
 

end

reclamos/app/views/causes/_form.html.erb
<%= form_for(@cause) do |f| %>
  <% if @cause.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cause.errors.count, "error") %> prohibited this cause from being saved:</h2>

      <ul>
      <% @cause.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :popularity %><br />
    <%= f.number_field :popularity %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.number_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

reclamos/app/views/causes/_form_with_complaint.html.erb
<%= form_tag create_with_complaint_causes_url do %>
  <% if @cause.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cause.errors.count, "error") %> prohibited this cause from being saved:</h2>

      <ul>
      <% @cause.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div>
    <strong>Empresa :</strong> <%= @company.name %>
  <%= hidden_field_tag :complaint_id, @complaint.id %>
  <%= hidden_field_tag :company_id, @company.id %> 
  <div class="field">
    <strong><%= label_tag :name,'Nombre de la causa' %></strong><br />
    <%= text_field_tag :name %>
  </div>
  <div class="field">
    <strong><%= label_tag :description,'Descripción' %></strong><br />
    <%= text_area_tag :description %>
  </div>
  <div class="actions">
    <%= submit_tag 'Enviar' %>
  </div>
<% end %>

reclamos/app/views/causes/create_with_complaint.html.erb
<%= 'complaint_id = ' + @complaint_id %>

reclamos/app/views/causes/defend.html.erb
<%= @variable %>

reclamos/app/views/causes/edit.html.erb
<h1>Editing cause</h1>

<%= render 'form' %>

<%= link_to 'Show', @cause %> |
<%= link_to 'Back', causes_path %>

reclamos/app/views/causes/index.html.erb
<h1>Causas</h1>

  <ul id='complaints_list'>
    <% @causes.each do |c| %>
      <li>
        <dl class="complaints">
          <span class="complaint_name"><%= link_to c.name,c, :title => 'Ver reclamo' %></span>
          <% if current_is_admin==true or (current_user==c.creator) %>
          <%= link_to (image_tag('eliminar.gif', :size => '20x20')) , c, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
          <br/>
            <% if c.users %>
              <span class='btn btn-primary btn-small'><%= c.users.length %> apoyo</span>
            <% end %>
            <% if c.creator %>
              por <strong><%= link_to c.creator.username,c.creator, :title =>'Ver creador' %></strong> >> <%= c.created_at %>
            <% else %>
              <%= I18n.localize(c.created_at,:format => :long) %>
            <% end %>
        </dl>
      </li>
    <% end %>
  </ul>

reclamos/app/views/causes/new.html.erb
<h1>Nueva causa</h1>

<%= render 'form' %>

<%= link_to 'Back', causes_path %>

reclamos/app/views/causes/new_with_complaint.html.erb
<h1>Nueva causa para el reclamo <%= '"'+ @complaint.name + '"'%></h1>

<%= render 'form_with_complaint' %>

reclamos/app/views/causes/show.html.erb
<div class='complaint'>
  <div class='complaint-container'>
      <span class='complaint-title'>
        <strong><%= @cause.name %></strong>
      </span>
      <p class='cause-info'>
        <span class='complaint-author'>
           <span class="creator_name">
              <% if @cause.creator != nil %>
                por <%= link_to @cause.creator.username, @cause.creator %>
              <% else %>
                El creador de esta causa ha abandonado la comunidad.
              <% end %>
           </span>
           <%= I18n.localize(@cause.created_at,:format => :long) %>
        </span>
        <span>
          <% if current_is_user %>
            <% if !@supports %>
              <%= link_to "Apoyar", support_cause_url(@cause), :class=> 'btn btn-primary btn-small'%>
            <% elsif @cause.creator == current_user %>
              <%= link_to 'Eliminar causa', @cause,method: :delete,:class=>'btn btn-danger btn-small'%>
              <% if @cause.state != 2 %>
                <%= link_to 'Marcar solucionado',solve_cause_path(@cause),:method=>:post,:class=>'btn btn-success btn-small' %>
              <% else %>
                <strong>Causa SOLUCIONADA</strong>
              <% end %>
            <% else %>
              <%= link_to "Desapoyar", unsupport_cause_url(@cause) %>
            <% end %>
          <% end %>
          <% if current_is_lawyer %>
            <% if @cause.lawyer == current_user %>
              <%=  "Abandonar" %>
            <% elsif @lawyer == nil %>
              <%= link_to "Defender", defend_cause_path(@cause), :method => :post, :class => 'btn btn-primary btn-small' %>
            <% end %>
          <% end %>
        </span>
      </p>
  </div>
</div>

<div id="cause-tabs">
    <ul>
        <li><a href="#tabs-1">Descripción</a></li>
        <li><a href="#tabs-2">Apoyos</a></li>
        <li><a href="#tabs-4">Reclamos asociados</a></li>
        <% if @cause.creator == current_user && @cause.lawyer == nil %>
          <li><a href="#tabs-3">Solicitudes de defensa</a></li>
        <% end %>
        <% if @lawyer == nil && current_is_lawyer %>
          <li><a href="#tabs-6">Defender</a></li>
        <% end %>
        <% if @cause.lawyer != nil %>
          <li><a href="#tabs-7">Defender</a></li>
        <% end %>
    </ul>
    <!-- TAB 1 -->
    <div id="tabs-1">
      <div class='complaint-container'>
            <span class='complaint_name'><strong>Descripcion</strong></span>
            <p class='complaint-description'>
              <%= @cause.description %>
            </p>
            <span class='complaint_name'><strong>Empresa</strong></span>
            <p class='complaint-description'>
              <%= link_to @cause.company.name,@cause.company %>
            </p>
      </div>
    </div>
    <!-- TAB 2 -->
    <div id="tabs-2">
        <% list_users(@users) do |u|%>
          <strong class="red"><%= link_to u.username, u %></strong><br>
        <% end %>
    </div>
    <!-- TAB 4 -->
    <div id="tabs-4">
        <% list_complaints(@complaints) do |c|%>
            <strong><%= link_to c.name, c %></strong><br>
        <% end %>
    </div>
    <!-- TAB 5 -->
    <% if @cause.creator == current_user && @cause.lawyer == nil %>
      <div id="tabs-3">
        <% if @cause.requesting_lawyers != nil && !@cause.requesting_lawyers.empty? %>
          Los siguientes abogados han solicitado defender esta causa
          <% @cause.requesting_lawyers.each do |l| %>
            <strong style="color:red"><%= link_to l.username, l %> <%= link_to "Aceptar", defend_cause_lawyer_path(l, :cause_id => @cause.id), :method => :post,:class=>"red" %></strong> 
        <% end %>
      <% else %>
        No hay abogados solicitando defender esta causa. 
        <% if current_user == @cause.creator %>
          Vea la <%= link_to "lista de abogados", lawyers_url,:class=>"red" %> para invitar abogados defender esta causa.
        <% end %>
      <% end %> 
      </div>
    <% end %>
    <!-- TAB 6 -->
    <div id="tabs-6">
      <% if @lawyer == nil && current_is_lawyer %>
        <% if @exists_request %>
          Tienes una petición de defensa enviada
        <%else %>
          Ningún abogado defiende esta causa. Usted puede ofrecerle su defensa y el creador de la causa podrá aceptarla o rechazarla. 
        <%= link_to "Enviar solicitud de defensa", defend_cause_path(@cause),:method => :post,:class=>'red' %>
        <%end%>
      <%end%>
    </div>
    <!-- TAB 7 -->
    <% if @cause.lawyer != nil %>
      <div id="tabs-7">
        El abogado defensor de esta causa es <%= link_to @lawyer.username, @lawyer,:class=>"red" %>. <%= link_to "Despedir", stop_defending_cause_lawyer_path(@lawyer, :cause_id => @cause.id), :method => :post, :class=>"red" %>
      </div>
    <% end %>
</div>

reclamos/app/views/causes/support.html.erb
<%if current_user == nil %>
Debes registrarte para apoyar una causa
<% else %>
Ya apoyas esta causa
<% end %>

reclamos/app/views/causes/unsupport.html.erb
<%if current_user == nil %>
Debes registrarte para apoyar una causa
<% else %>
Ya no apoyabas esta causa
<% end %>